In [10]:
import numpy as np 
import pandas as pd 
import statistics as st
realfile = pd.read_csv("16P.csv", encoding = "ISO-8859-1")
print(realfile)


       Response Id  You regularly make new friends.  \
0                0                                0   
1                1                                0   
2                2                                0   
3                3                                0   
4                4                                0   
...            ...                              ...   
59994        59994                                0   
59995        59995                                0   
59996        59996                                0   
59997        59997                                0   
59998        59998                                0   

       You spend a lot of your free time exploring various random topics that pique your interest  \
0                                                      0                                            
1                                                      0                                            
2                                   

In [11]:
analyzedfile = realfile.drop("Response Id",1)
purefile = analyzedfile.drop("Personality",1)
print(analyzedfile)

       You regularly make new friends.  \
0                                    0   
1                                    0   
2                                    0   
3                                    0   
4                                    0   
...                                ...   
59994                                0   
59995                                0   
59996                                0   
59997                                0   
59998                                0   

       You spend a lot of your free time exploring various random topics that pique your interest  \
0                                                      0                                            
1                                                      0                                            
2                                                      0                                            
3                                                     -1                                   

C:\Users\biret\AppData\Local\Temp\ipykernel_22372\1531273343.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  analyzedfile = realfile.drop("Response Id",1)
C:\Users\biret\AppData\Local\Temp\ipykernel_22372\1531273343.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  purefile = analyzedfile.drop("Personality",1)


In [12]:
def encode():
    analyzedfile["Personality"] = analyzedfile["Personality"].replace(["ESTJ"], 0).replace(["ENTJ"],1).replace(["ESFJ"],2).replace(["ENFJ"],3).replace(["ISTJ"],4).replace("ISFJ",5).replace("INTJ",6).replace("INFJ",7).replace("ESTP",8).replace("ESFP",9).replace("ENTP",10).replace("ENFP",11).replace("ISTP",12).replace("ISFP",13).replace("INTP",14).replace("INFP",15)
encode()
personality = analyzedfile["Personality"]
mypersonality =[]
print(personality)

0        11
1        13
2         7
3        12
4         3
         ..
59994     7
59995     8
59996    12
59997     4
59998     7
Name: Personality, Length: 59999, dtype: int64


In [13]:
personality = np.array(analyzedfile["Personality"])
thefile = np.array(purefile)
print(thefile)

[[ 0  0  0 ...  0  0  0]
 [ 0  0 -2 ... -1 -1  3]
 [ 0  0  2 ...  1  2  1]
 ...
 [ 0  0  1 ... -1  0 -1]
 [ 0  0  1 ...  0  1  0]
 [ 0  0  2 ...  1  0 -1]]


zaten 5 tane dosya döndüreceğimiz için hepsini ayrı ayrı yazmakta sıkıntı görmedim.

In [14]:
a = thefile[0:12000]
b = thefile[12000:24000]
c = thefile[24000:36000]
d = thefile[36000:48000]
e = thefile[48000:60000]
k1 = personality[0:12000]
k2 = personality[12000:24000]
k3 = personality[24000:36000]
k4 = personality[36000:48000]
k5 = personality[48000:60000]


In [15]:
def distances(testfile, trainfile):
    transposed = trainfile.T
    x2 = np.sum(testfile**2,1)
    y2 = np.sum(trainfile**2,1)
    xy = np.matmul(testfile, transposed)*2
    x2 = x2.reshape(-1,1)
    distance = (x2 -xy + y2)**0.5
    return distance

In [16]:
def prediction(c,k):
    for i in c[:,:k]:
        global mypersonality        
        mypersonality.append(st.mode(i))
    mypersonality = np.array(mypersonality)

In [17]:
def creatingconfusionmatrix(personality1):
    confusion_matrix = np.zeros([16, 16])
    np.add.at(confusion_matrix, (personality1 - 1, mypersonality - 1), 1)
    recall = np.sum(np.diag(confusion_matrix) / np.sum(confusion_matrix,1))/16
    precision = np.sum(np.diag(confusion_matrix) / np.sum(confusion_matrix,0))/16
    accuracy = np.sum(np.diag(confusion_matrix)) / np.sum(confusion_matrix)
    print("Recall: ", recall)
    print("Precision: ", precision)
    print("Accuracy: ", accuracy)

In [18]:
try:
 for k in range(1,10,2):
    if k == 1:        
        result = distances(a,thefile[12000:])
        personality1 = np.array(analyzedfile["Personality"][12000:])
        result = np.argsort(result)
        comparingresult = personality1[result]
        prediction(comparingresult,k)
        creatingconfusionmatrix(k1)
        print("-------------------------------")
        mypersonality =[]
    if k == 3:
        result = distances(b,thefile[24000:])
        personality1 = np.array(analyzedfile["Personality"][24000:])
        result = np.argsort(result)
        comparingresult = personality1[result]
        prediction(comparingresult,k)
        creatingconfusionmatrix(k2)
        print("-------------------------------")
        mypersonality =[]
    if k == 5:
        result = distances(c,thefile[36000:])
        personality1 = np.array(analyzedfile["Personality"][36000:])
        result = np.argsort(result)
        comparingresult = personality1[result]
        prediction(comparingresult,k)
        creatingconfusionmatrix(k3)
        print("-------------------------------")
        mypersonality =[]
    if k == 7:
        result = distances(d,thefile[:36000])
        personality1 = np.array(analyzedfile["Personality"][:36000])
        result = np.argsort(result)
        comparingresult = personality1[result]
        prediction(comparingresult,k)
        creatingconfusionmatrix(k4)
        print("-------------------------------")
        mypersonality =[]
    if k == 9:
        result = distances(e,thefile[:48000])
        personality1 = np.array(analyzedfile["Personality"][:48000])
        result = np.argsort(result)
        comparingresult = personality1[result]
        prediction(comparingresult,k)
        creatingconfusionmatrix(k5)
        print("-------------------------------")
        mypersonality =[]
except IndexError:
    print("some values are missing")
    pass
 
        
        
        

Recall:  0.9786130922017358
Precision:  0.9786650790937741
Accuracy:  0.9786666666666667
-------------------------------
Recall:  0.9885769222258489
Precision:  0.9885632152811226
Accuracy:  0.9885833333333334
-------------------------------
Recall:  0.9892964108810225
Precision:  0.989280362499162
Accuracy:  0.98925
-------------------------------
Recall:  0.9885809646416426
Precision:  0.9886031033458449
Accuracy:  0.9885833333333334
-------------------------------
Recall:  0.989066798059014
Precision:  0.9890744890633165
Accuracy:  0.9890824235352946
-------------------------------


In [19]:
def feature_scaling(file):
    min = np.min(file, 0)
    max = np.max(file, 0)
    file = (file - min) / (max - min)
    return file
thefile = feature_scaling(thefile)
print(thefile)

[[0.66666667 0.5        0.5        ... 0.5        0.5        0.5       ]
 [0.66666667 0.5        0.16666667 ... 0.33333333 0.33333333 1.        ]
 [0.66666667 0.5        0.83333333 ... 0.66666667 0.83333333 0.66666667]
 ...
 [0.66666667 0.5        0.66666667 ... 0.33333333 0.5        0.33333333]
 [0.66666667 0.5        0.66666667 ... 0.5        0.66666667 0.5       ]
 [0.66666667 0.5        0.83333333 ... 0.66666667 0.5        0.33333333]]


In [20]:
a = thefile[0:12000]
b = thefile[12000:24000]
c = thefile[24000:36000]
d = thefile[36000:48000]
e = thefile[48000:60000]
k1 = personality[0:12000]
k2 = personality[12000:24000]
k3 = personality[24000:36000]
k4 = personality[36000:48000]
k5 = personality[48000:60000]

In [21]:
try:
 for k in range(1,10,2):
    if k == 1:        
        result = distances(a,thefile[12000:])
        personality1 = np.array(analyzedfile["Personality"][12000:])
        result = np.argsort(result)
        comparingresult = personality1[result]
        prediction(comparingresult,k)
        creatingconfusionmatrix(k1)
        print("-------------------------------")
        mypersonality =[]
    if k == 3:
        result = distances(b,thefile[24000:])
        personality1 = np.array(analyzedfile["Personality"][24000:])
        result = np.argsort(result)
        comparingresult = personality1[result]
        prediction(comparingresult,k)
        creatingconfusionmatrix(k2)
        print("-------------------------------")
        mypersonality =[]
    if k == 5:
        result = distances(c,thefile[36000:])
        personality1 = np.array(analyzedfile["Personality"][36000:])
        result = np.argsort(result)
        comparingresult = personality1[result]
        prediction(comparingresult,k)
        creatingconfusionmatrix(k3)
        print("-------------------------------")
        mypersonality =[]
    if k == 7:
        result = distances(d,thefile[:36000])
        personality1 = np.array(analyzedfile["Personality"][:36000])
        result = np.argsort(result)
        comparingresult = personality1[result]
        prediction(comparingresult,k)
        creatingconfusionmatrix(k4)
        print("-------------------------------")
        mypersonality =[]
    if k == 9:
        result = distances(e,thefile[:48000])
        personality1 = np.array(analyzedfile["Personality"][:48000])
        result = np.argsort(result)
        comparingresult = personality1[result]
        prediction(comparingresult,k)
        creatingconfusionmatrix(k5)
        print("-------------------------------")
        mypersonality =[]
except IndexError:
    print("some values are missing")
    pass

Recall:  0.9736894383915659
Precision:  0.9737131084616033
Accuracy:  0.9736666666666667
-------------------------------
Recall:  0.987922031008418
Precision:  0.9879136289394497
Accuracy:  0.9879166666666667
-------------------------------
Recall:  0.9892128327041
Precision:  0.9891857551095417
Accuracy:  0.9891666666666666
-------------------------------
Recall:  0.9877984354799654
Precision:  0.9878589299551045
Accuracy:  0.9878333333333333
-------------------------------
Recall:  0.988309989356427
Precision:  0.9883220099495479
Accuracy:  0.9883323610300858
-------------------------------
